#!/bin/bash

if [ -z "$1" ] || [ $# -gt 1 ] || [ "$1" = "--help" ] || [ "$1" = "-h" ]; then
    echo "Usage: $0 username"
    echo "This can be used to update the configs for another user from the current user"
    exit 1
fi
# check name validity as POSIX rule and sanitize
if [[ ! "$1" =~ ^[a-z][a-z0-9_-]{0,31}$ ]]; then
    echo "Error: Invalid username '$1'" >&2
    exit 1
fi
_user="$1"
if ! getent passwd "$_user" > /dev/null 2>&1; then
    echo "Error: user $_user doesn't exist" >&2
    exit 1
else
    _userhome="$(getent passwd "$_user" | cut -d: -f6)"
    _usergrp="$(getent passwd "$_user" | cut -d: -f4)"
    if [ -z "$_userhome" ];then
        echo "Error: user $_user doesn't have home directory" >&2
        exit 1
    fi
fi

script_dir="$(dirname "$(realpath -- "${BASH_SOURCE[0]}")")"
echo "Target user is ${_user}($_userhome)"
echo "Current user is $(whoami)"
if [[ "$(whoami)" != "$_user" ]]; then
    echo "Installing for different target user. Require root access."
    sudo -v
    _cmd_prefix="sudo"
fi

# install dotfiles to <user> home
echo "[INFO] Installing dot files to $_userhome"
${_cmd_prefix} rsync -av --chown="${_user}:${_usergrp}" "${script_dir:?}"/{.bash_profile,.bashrc,.xkb} "$_userhome/"

for f in "${script_dir:?}"/config/*; do
    ${_cmd_prefix} rsync -a --chown="${_user}:${_usergrp}" --delete "$f" "$_userhome/.config/"
done

for f in etc/*; do
    echo "Checking for file $f"
    source_sum=$(sha256sum "$f" | awk '{print $1}')
    dest_sum=$(sha256sum /etc/"$(basename "$f")" 2> /dev/null | awk '{print $1}')
    if [[ "$source_sum" != "$dest_sum" ]]; then
        echo "Updating $f"
        sudo rsync -a --chown="root:root" "$f" /etc/"$(basename "$f")"
    fi
done
