#!/bin/bash

script_dir="$(dirname "$(realpath -- "${BASH_SOURCE[0]}")")"

rm -rf "${script_dir:?}/config" && echo "Removed old config dir"
rm -rf "${script_dir:?}/etc" && echo "Removed old etc dir"

for i in .bash_profile .bashrc .xkb; do
    rsync -a --delete "$HOME/$i" "$script_dir/"
done
_configs="
 foot
 fuzzel
 lf
 mako
 mimeapps.list
 mpv
 nvim
 sway
 swayimg
 swayosd
 swaync
 xdg-desktop-portal-termfilechooser
 waybar
 wofi
"
for i in $_configs; do
    rsync -a --delete "$HOME/.config/$i" "$script_dir/config/"
done

rsync -pt /etc/{issue,rc.local} "$script_dir/etc/"
