#!/bin/bash

set -eu

script_dir="$(dirname "$(realpath -- "${BASH_SOURCE[0]}")")"

rm -rf "${script_dir:?}/config" && echo "Removed old config dir"
rm -rf "${script_dir:?}/etc" && echo "Removed old etc dir"

_configs="
 foot
 fuzzel
 imv
 lf
 mako
 mimeapps.list
 mpv
 nvim
 service
 sway
 swayimg
 swayosd
 swaync
 xdg-desktop-portal-termfilechooser
 waybar
 wofi
 yt-dlp
"

_home="
 .newsboat
 .xkb
 .bash_profile
 .bashrc
"

echo "Updating config dir"
for i in $_configs; do
    rsync -a --delete "$HOME/.config/$i" "$script_dir/config/"
done

echo "Updating home config dirs"
for i in $_home; do
    rsync -a --delete "$HOME/$i" "$script_dir/home/"
done

echo "Updating config in /etc/"
rsync -pt /etc/{issue,rc.local} "$script_dir/etc/"
